theme: jekyll-theme-cayman
title:  Vidyapith
description:  An International Foundation for the Advancement of Education in relation to the Eradication of Poverty in India
tagline:  An International Foundation for the Advancement of Education in relation to the Eradication of Poverty in India
logo: "assets/logo/logo3.png"
author: Surajit Ray
defaults:
  # _docs
  - scope:
      path: "images/"
      type: docs
    values:
      sidebar:
        nav: "docs"
github:
  is_project_page: false
